name: scaling_header
description: Scaling header(appBar) with scroll interactions
version: 2.0.0
author: Figen Güngör <figengungor1@gmail.com>
homepage: https://github.com/figengungor/scaling_header

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
